name: Sync to Notion

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git diff
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            **/*.md
            **/*.py
            **/*.js
            **/*.ts
            **/*.jsx
            **/*.tsx

      - name: Debug Changed Files
        run: |
          echo "Any files changed: ${{ steps.changed-files.outputs.any_changed }}"
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Sync files to Notion
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ -z "${{ secrets.VERCEL_SYNC_URL }}" ]; then
            echo "Error: VERCEL_SYNC_URL is not set"
            exit 1
          fi
          
          if [ -z "${{ secrets.NOTION_TOKEN }}" ]; then
            echo "Error: NOTION_TOKEN is not set"
            exit 1
          fi

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ -f "$file" ]; then
              echo "Processing file: $file"
              content=$(cat "$file" | base64 -w 0)
              response=$(curl -s -w "\n%{http_code}" -X POST ${{ secrets.VERCEL_SYNC_URL }} \
                -H "Content-Type: application/json" \
                -d "{
                  \"notion_token\": \"${{ secrets.NOTION_TOKEN }}\",
                  \"github_token\": \"${{ secrets.GITHUB_TOKEN }}\",
                  \"repo_name\": \"${{ github.repository }}\",
                  \"file_path\": \"$file\",
                  \"content\": \"$content\",
                  \"file_pattern\": \"**/*.{md,py,js,ts,jsx,tsx}\"
                }")
              
              status_code=$(echo "$response" | tail -n1)
              body=$(echo "$response" | sed '$d')
              
              echo "Response status: $status_code"
              echo "Response body: $body"
              
              if [ "$status_code" != "200" ]; then
                echo "Error syncing file $file"
                exit 1
              fi
            fi
          done 
